version: '3'
services:
  mysql:
    image: mariadb:latest
    container_name: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
    networks:
      - mns
  metadata:
    container_name: metadata
    build: https://github.com/monadns/mns-metadata-service.git
    ports:
      - '8080:8080'
    networks:
      - mns
    restart: always
    environment:
      NODE_PROVIDER_URL: ${METADATA_NODE_PROVIDER_URL}
      GRAPH_API_URL: ${METADATA_GRAPH_API_URL}
      ADDRESS_ETH_REGISTRY: ${METADATA_ADDRESS_ETH_REGISTRY}
      ADDRESS_ETH_REGISTRAR: ${METADATA_ADDRESS_ETH_REGISTRAR}
  api:
    container_name: api
    build: https://github.com/monadns/mns-api.git
    ports:
      - '3000:3000'
    networks:
      - mns
    restart: always
    environment:
      PORT: ${API_PORT}
      NODE_ENV: ${API_NODE_ENV}
      OG_DEFAULT_IMAGE_URL: ${API_OG_DEFAULT_IMAGE_URL}
      OG_IMAGE_URL: ${API_OG_IMAGE_URL} 
    volumes:
      - './dist/:/usr/local/app/dist'
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_CONFIG_EXTRA: "${WORDPRESS_CONFIG_EXTRA}"
    depends_on:
      - mysql
      - phpmyadmin 
    restart: always
    ports:
      - 8081:80
    networks:
      - mns
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql 
    restart: always
    ports:
      - 8180:80
    environment:
      PMA_HOST: ${PMA_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - mns
  nginx:
    container_name: nginx
    image: 'nginx:latest'
    restart: always
    depends_on:
      - wordpress
      - metadata
      - phpmyadmin
      - api
    networks:
      - mns
    ports:
      - '80:80'
      - '443:80'
    volumes:
      - './nginx/conf.d:/etc/nginx/conf.d'
      - './dist:/usr/share/nginx/html'
networks:
  mns: null
